# Generated by Django 5.1.4 on 2024-12-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='configitemvalue',
            constraint=models.UniqueConstraint(fields=('item', 'environment'), name='unique_item_per_environment'),
        ),
    ]
