# Generated by Django 5.1.4 on 2024-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configitem',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Env'), (2, 'File'), (3, 'Ref')]),
        ),
    ]
