# Generated by Django 5.1.4 on 2024-12-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adapterconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adapterconfig',
            old_name='conifg',
            new_name='config',
        ),
    ]
